spring:
    jpa:
        hibernate:
            ddl-auto: create-drop
            generate-ddl: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQL95Dialect
    datasource:
        driver-class: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/jugistanbul
        username: postgres
        password: postgres
