spring.jpa:
  properties:
    hibernate.search:
      schema_management:
        strategy: drop_and_create
      automatic_indexing:
        synchronization:
          strategy: sync
      backend:
        hosts: http://localhost:9200
        protocol: http
        discovery.enabled: true
        analysis.configurer: englishAnalysisConfigurer